<<<<<<< HEAD

image: node:argon
git:
  path: github.com/clijockey/migginsbot
  commands:
      - echo "build commands"
      - .shipped/build
      - echo "Run commands;"
      - .shipped/run
      - echo "Test commands;"
      - .shipped/test
=======
build:
  image: node:argon
  commands:
  - echo "build commands"
  - echo "no build command"
  - echo "no test command"
>>>>>>> d157c727660d60d84d3250e1a87ff22ddd26ce97
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
