build:
  image: node:argon
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
