image: node:argon
git:
  path: github.com/clijockey/migginsbot
script:
  - echo "build commands"
  - .shipped/build
  - echo "run command"
  - .shipped/run
  - echo "test command"
  - .shipped/test
clone:
  path: github.com/clijockey/migginsbot
build:
  image: node:argon
  commands:
      - echo "build commands"
      - .shipped/build
      - echo "run command"
      - .shipped/run
      - echo "test command"
      - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
tag: $$COMMIT
